### ISSUE TITLE
rust-lang/rust integration metabug

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/compiler-builtins#66]
- [x] Build missing intrinsics from compiler-rt (C) source code #63
- [x] Put weak memcpy et al symbols behind an opt-in Cargo feature #64
- [x] Test our implementations against libgcc #65 
- [x] Rename this repo to compiler-builtins
- [x] Transfer to rust-lang-nursery
- [x] compile functions with hidden visibility
- [x] i128 support - #133 
- [x] "C" ABI -> "aapcs" on ARM - #116 #141

cc @alexcrichton

**Comment by est31** [comment]
Note, now that https://github.com/rust-lang/rust/pull/38482 is merged, i128 support is required as well.

Just using the C implementation is not enough as the C implementation only is enabled and works on non windows 64 bit platforms (that was the reason the PR had to implement the intrinsics in Rust in the first place).

See #133 that attempts to add support.

Also note that during the making of that PR I not just had linker issues with calls to panic, it also complained about calls to eh_personality, which in some cases survives while panic does not.

**Comment by japaric** [comment]
Added i128 support to the list. After #133 lands, we would still need the famility of floatundif intrinsics, I believe.

Also added changing the ABI of (some?) intrinsics from C to aapcs on ARM. cc #116 

> compile functions with hidden visibility

And I believe this issue was fixed in rust-lang/rust proper? cc @alexcrichton

**Comment by est31** [comment]
With #133 merged, the following float functions are required to be ported:

* `__fixsfti`
* `__fixdfti`
* `__fixunsdfti`
* `__fixunssfti`
* `__floattidf`
* `__floattisf`
* `__floatuntidf`
* `__floatuntisf`

They all need `extern "unadjusted"` instead of `extern "C"` on windows.

**Comment by japaric** [comment]
>  "C" ABI -> "aapcs" on ARM - #116 #141

I think that powisf2 and powidf2 may need to be changed to AAPCS too. Honestly, I'm no longer sure what's the state of those intrinsics on LLVM 3.9 vs 4.0.

**Comment by japaric** [comment]
OK. I believe that all the required intrinsics to land this in rust-lang/rust have been implemented. All that's left is: (a) check that the compiler-rt submodule in this repo matches the revision being used in rust-lang/rust and then (b) fight with bors and land this in rust-lang/rust.

Any volunteers? Here's what needs to be done for (b):

- Remove the `src/libcompiler_builtins` directory in rust-lang/rust
- Replace it with a git submodule that points to this repo
- Create a libcompiler_builtins_shim Cargo project that builds this repo with the right Cargo features (the "rustbuild" feature). The std crate will depend on that shim. (I lost track of the comment that explained why the shim was necessary. Sorry)
- Likely update the part of the boostrap tool that cares of building the sanitizers' runtimes to use the new location of the compiler-rt code. (src/compiler-rt -> src/libcompiler_builtins/compiler-rt)

All in one PR. You should test locally as a sanity check and then we can feed it to bors.

Here's an old attempt of mine: rust-lang/rust#37802. All the Makefile changes in that PR won't be necessary as the Makefiles have been removed.

**Comment by est31** [comment]
Not a volunteer, but as someone who had a good share of "fighting with bors", I wish anyone who mounts an attempt the best of luck.

**Comment by japaric** [comment]
@est31 Hey, don't scare the volunteers!

**Comment by alexcrichton** [comment]
Done now!
